/* 
╭━━━╮╱╱╱╱╭╮╱╱╱╱╱╱╭╮╭━━━╮
┃╭━━╯╱╱╱╱┃┃╱╱╱╱╱╭╯┃┃╭━╮┃
┃╰━━┳━━┳━╯┣━━┳━━╋╮┃┃┃┃┃┃
┃╭━━┫┃━┫╭╮┃┃━┫━━┫┃┃┃┃┃┃┃
┃┃╱╱┃┃━┫╰╯┃┃━╋━━┣╯╰┫╰━╯┃
╰╯╱╱╰━━┻━━┻━━┻━━┻━━┻━━━╯
╭━━━╮╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱╭╮╱╭╮
┃╭━╮┃╱╱╱╱╱╱╱╱╱╱╱╱╱╱╱┃┃╭╯╰╮
┃┃╱╰╋━━┳━━┳╮╱╭┳━┳┳━━┫╰┻╮╭╯
┃┃╱╭┫╭╮┃╭╮┃┃╱┃┃╭╋┫╭╮┃╭╮┃┃
┃╰━╯┃╰╯┃╰╯┃╰━╯┃┃┃┃╰╯┃┃┃┃╰╮
╰━━━┻━━┫╭━┻━╮╭┻╯╰┻━╮┣╯╰┻━╯
╱╱╱╱╱╱╱┃┃╱╭━╯┃╱╱╱╭━╯┃
╱╱╱╱╱╱╱╰╯╱╰━━╯╱╱╱╰━━╯


© 2026 Federico Lora 
*/
// Calendario de santos católicos organizados por mes-día
// Cuando hay varios santos en un día, se devuelven todos en un array
const SANTOS_CALENDARIO = {
    "1-1": ["Santa María, Madre de Dios", "Emmanuel"],
    "1-2": ["San Basilio Magno", "San Gregorio Nazianceno"],
    "1-3": ["Santa Estefanía Quinzani", "Santa Genoveva"],
    "1-4": ["San Rigoberto", "Santa Ángela de Foligno"],
    "1-5": ["San Juan Nepomuceno Neumann", "San Simeón el Estilita"],
    "1-6": "Epifanía del Señor",
    "1-7": "San Raimundo de Peñafort",
    "1-8": "Santa Gúdula",
    "1-9": ["San Eulogio de Córdoba", "Santa Lucrecia de Córdoba"],
    "1-10": "Beata María Dolores Rodríguez Sopeña",
    "1-11": "Santo Tomás de Cori Placidi",
    "1-12": "San Benito Biscop",
    "1-13": "San Hilario de Poitiers",
    "1-14": "San Félix de Nola",
    "1-15": ["San Mauro", "Santa Raquel"],
    "1-16": "San Marcelo I",
    "1-17": "San Antonio Abad",
    "1-18": "Santa Prisca",
    "1-19": "Beato Marcelo Spínola",
    "1-20": ["San Fabián", "San Sebastián"],
    "1-21": ["San Fructuoso de Tarragona", "Santa Inés"],
    "1-22": ["San Vicente", "Beata Laura Vicuña"],
    "1-23": "San Ildefonso",
    "1-24": "San Francisco de Sales",
    "1-25": "San Pablo en su conversión",
    "1-26": ["San Timoteo", "San Tito"],
    "1-27": ["San Enrique de Ossó", "Santa Ángela de Mérici"],
    "1-28": "Santo Tomás de Aquino",
    "1-29": "San Pedro Nolasco",
    "1-30": "Santa Martina de Roma",
    "1-31": ["San Juan Bosco", "Santa Marcela"],
    
    "2-1": "Santa Brígida de Irlanda",
    "2-2": "Nuestra Señora de la Purificación",
    "2-3": ["San Blas", "San Oscar"],
    "2-4": ["San Gilberto de Sempringham", "Santa Juana de Valois"],
    "2-5": ["San Felipe de Jesús", "Santa Águeda"],
    "2-6": ["San Pablo Miki", "Santa Dorotea"],
    "2-7": "San Ricardo",
    "2-8": "San Jerónimo Emiliani",
    "2-9": "Santa Apolonia de Alejandría",
    "2-10": "Santa Escolástica de Nursia",
    "2-11": ["San Pedro de Jesús Maldonado", "Virgen de Lourdes"],
    "2-12": "Santa Eulalia de Barcelona",
    "2-13": "San Benigno de Todi",
    "2-14": ["San Cirilo", "San Metodio", "San Valentín"],
    "2-15": "Beato Onésimo",
    "2-16": "Santa Juliana de Nicodemia",
    "2-17": "San Teodoro de Bizancio",
    "2-18": "San Eladio",
    "2-19": "Beato Álvaro de Córdoba",
    "2-20": "Beata Jacinta Marto",
    "2-21": "San Pedro Damián",
    "2-22": ["San Maximiano de Ravena", "San Pascasio"],
    "2-23": "San Policarpo",
    "2-24": ["San Modesto", "San Sergio de Capadocia"],
    "2-25": "San Valerio de Astorga",
    "2-26": ["San Alejandro", "San Porfirio"],
    "2-27": "San Gabriel de la Dolorosa",
    "2-28": "San Leandro de Sevilla",
    "2-29": "San Dositeo",
    
    "3-1": "San David de Gales",
    "3-2": "San Simplicio",
    "3-3": "San Emeterio de Calahorra",
    "3-4": "San Casimiro",
    "3-5": "San Adriano",
    "3-6": ["San Julián", "San Olegario"],
    "3-7": ["Santa Felicidad", "Santa Perpetua"],
    "3-8": "San Juan de Dios",
    "3-9": "Santa Catalina de Bolonia",
    "3-10": "Santa María Eugenia de Jesús",
    "3-11": "Santa Áurea de San Millán",
    "3-12": ["San Inocencio I", "San Maximiliano de Tebeste"],
    "3-13": "Santa Cristina",
    "3-14": "Santa Matilde",
    "3-15": "San Raimundo de Fitero",
    "3-16": "Patriarca Abraham",
    "3-17": ["San José de Arimatea", "San Patricio"],
    "3-18": "San Cirilo de Jerusalén",
    "3-19": "San José",
    "3-20": "San Martín de Dumio",
    "3-21": "San Nicolás de Flüe",
    "3-22": "San Bienvenido Scotivoli",
    "3-23": ["San José Oriol", "Santo Toribio de Mogrovejo"],
    "3-24": "Santa Catalina de Suecia",
    "3-25": ["San Dimas", "Anunciación del Señor"],
    "3-26": "San Braulio de Zaragoza",
    "3-27": "San Ruperto de Worms",
    "3-28": "San Sixto III",
    "3-29": "San Eustasio de Luxeüil",
    "3-30": "San Zósimo de Siracusa",
    "3-31": ["San Amós", "San Renato de Mérida"],
    
    "4-1": "San Hugo de Grenoble",
    "4-2": "San Francisco de Paula",
    "4-3": "San Ricardo de Wyche",
    "4-4": "San Benito Massarari",
    "4-5": "San Vicente Ferrer",
    "4-6": "Santa Gala",
    "4-7": "San Juan Bautista de la Salle",
    "4-8": ["San Dionisio de Corinto", "Santa Julia Billiart"],
    "4-9": "Santa Casilda de Toledo",
    "4-10": "San Ezequiel",
    "4-11": ["San Estanislao", "San Isaac de Spoleto", "Santa Gemma Galgani"],
    "4-13": "San Hermenegildo",
    "4-14": "Santa Lidia de Schiedam",
    "4-15": "San Telmo",
    "4-16": "Santa Engracia",
    "4-17": "San Aniceto",
    "4-18": "San Perfecto",
    "4-19": ["San Expedito", "San León IX"],
    "4-20": "Santa Inés de Montepulciano",
    "4-21": "San Anselmo de Canterbury",
    "4-22": "San Sotero",
    "4-23": "San Jorge",
    "4-24": "San Fidel de Sigmaringen",
    "4-25": "San Marcos Evangelista",
    "4-26": "San Isidoro de Sevilla",
    "4-27": ["San Pedro Armengol", "Santa Zita", "Virgen de Montserrat"],
    "4-28": ["San Luis María Grignon", "San Pedro Chanel", "San Prudencio"],
    "4-29": ["San Hugo", "Santa Catalina de Siena"],
    "4-30": ["San José Benito Cottolengo", "San Pío V"],
    
    "5-1": ["San Jeremías", "San José Obrero"],
    "5-2": "San Atanasio",
    "5-3": ["San Felipe", "Santiago el Menor"],
    "5-4": "San Godofredo de Hildesheim",
    "5-5": ["San Ángel de Sicilia", "San Hilario de Arlés"],
    "5-6": "Santo Domingo Savio",
    "5-7": "San Juan de Beverley",
    "5-8": ["San Pedro de Tarantasia", "Virgen de Luján"],
    "5-9": ["San Gregorio Ostiense", "San Isaías"],
    "5-10": ["San Damián de Molokai", "Santo Job"],
    "5-11": "San Mayolo de Cluny",
    "5-12": ["San Pancracio", "Santo Domingo de la Calzada"],
    "5-13": ["San Pedro de Regalado", "Virgen de Fátima"],
    "5-14": "San Matías Apóstol",
    "5-15": "San Isidro Labrador",
    "5-16": "San Simón Stock",
    "5-17": "San Pascual Bailón",
    "5-18": "Santa Claudia",
    "5-19": ["San Ivo", "San Pedro Celestino"],
    "5-20": "San Bernardino de Siena",
    "5-21": "San Cristóbal Magallanes",
    "5-22": ["Santa Joaquina de Vedruna", "Santa Rita de Casia"],
    "5-23": "San Desiderio de Langres",
    "5-24": "María Auxiliadora",
    "5-25": ["San Beda el Venerable", "San Gregorio VII", "Santa María Magdalena de Pazzi"],
    "5-26": ["San Felipe Neri", "Santa Mariana de Jesús"],
    "5-27": "San Agustín de Cantorbery",
    "5-28": ["San Germán de París", "San Guillermo de Gelona"],
    "5-29": "San Maximino de Tréveris",
    "5-30": ["San Fernando III", "Santa Juana de Arco"],
    "5-31": "Santa Petronila de Roma",
    
    "6-1": ["San Justino", "Virgen de la Luz"],
    "6-2": ["San Marcelino", "San Pedro"],
    "6-3": "San Carlos Lwanga",
    "6-4": ["Santa Noemí", "Santa Ruth"],
    "6-5": "Beato Fernando de Portugal",
    "6-6": "San Marcelino Champagnat",
    "6-7": "San Isaac de Córdoba",
    "6-8": "San Medardo",
    "6-9": ["San Efrén de Siria", "Beata Ana María Taigi"],
    "6-10": "San Asterio de Petra",
    "6-11": "San Bernabé Apóstol",
    "6-12": "San Onofre de Egipto",
    "6-13": ["San Antonio de Padua", "San Fandila"],
    "6-14": ["San Anastasio", "San Eliseo", "San Félix", "Santa Digna"],
    "6-15": ["Santa Benilde", "Santa María Micaela"],
    "6-16": "San Juan Francisco Regis",
    "6-17": "Santa Teresa de Portugal",
    "6-18": ["San Marcelino de Roma", "San Marcos de Roma"],
    "6-19": ["San Gervasio", "San Protasio", "San Romualdo"],
    "6-20": "Beato Tomás Whitbread",
    "6-21": "San Luis Gonzaga",
    "6-22": "Santo Tomás Moro",
    "6-23": "San José Cafasso",
    "6-24": "San Juan Bautista (Natividad)",
    "6-25": "San Máximo de Turín",
    "6-26": ["San Josemaría Escrivá", "San Pelayo"],
    "6-27": "San Cirilo de Alejandría",
    "6-28": "San Ireneo de Lyon",
    "6-29": ["San Pablo", "San Pedro"],
    "6-30": "San Ladislao de Hungría",
    
    "7-1": ["San Aarón", "Santa Ester"],
    "7-2": "San Otón de Bamberg",
    "7-3": "Santo Tomás Apóstol",
    "7-4": "Santa Isabel de Portugal",
    "7-5": "San Antonio María Zaccaría",
    "7-6": "Santa María Goretti",
    "7-7": "San Fermín",
    "7-8": "San Procopio",
    "7-9": ["San Nicolás Pieck", "Santa Verónica Giuliani"],
    "7-10": "San Cristóbal de Licia",
    "7-11": "San Benito de Nursia",
    "7-12": "San Juan Gualberto",
    "7-13": ["San Enrique", "Santa Teresa de los Andes"],
    "7-14": "San Camilo de Lelis",
    "7-15": "San Buenaventura",
    "7-16": "Virgen del Carmen",
    "7-17": "San Alejo",
    "7-18": ["San Federico de Utrecht", "Santa Sinforosa"],
    "7-19": "Santa Áurea de Córdoba",
    "7-20": "San Elías",
    "7-21": ["San Daniel", "San Lorenzo de Brindisi"],
    "7-22": "Santa María Magdalena",
    "7-23": "Santa Brígida de Suecia",
    "7-24": "Santa Cristina de Bolsena",
    "7-25": "Santiago el Mayor",
    "7-26": ["San Joaquín", "Santa Ana"],
    "7-27": ["San Cucufate", "San Simeón Estilita", "Santa Natalia"],
    "7-28": "San Víctor I",
    "7-29": "Santa Marta de Betania",
    "7-30": "San Pedro Crisólogo",
    "7-31": "San Ignacio de Loyola",
    
    "8-1": ["San Alfonso María de Ligorio", "San Pedro Fabro"],
    "8-2": "Virgen de los Ángeles",
    "8-3": "San Asprenato de Nápoles",
    "8-4": ["San Juan María Vianney", "San Rubén"],
    "8-5": "Virgen de las Nieves",
    "8-6": "San Hormisda",
    "8-7": ["San Cayetano de Thiene", "San Sixto II"],
    "8-8": "Santo Domingo de Guzmán",
    "8-9": ["San Osvaldo", "Santa Edith Stein"],
    "8-10": "San Lorenzo",
    "8-11": "Santa Clara de Asís",
    "8-12": "Santa Hilaria de Augsburgo",
    "8-13": "San Hipólito",
    "8-14": ["San Alfredo", "San Maximiliano Kolbe"],
    "8-15": ["Asunción de María", "Santa María del Alba"],
    "8-16": "San Roque",
    "8-17": "San Eusebio",
    "8-18": "Santa Elena de Constantinopla",
    "8-19": "San Juan Eudes",
    "8-20": ["San Bernardo de Claraval", "San Samuel"],
    "8-21": "San Pío X",
    "8-22": "Santa María Reina",
    "8-23": "Santa Rosa de Lima",
    "8-24": "San Bartolomé Apóstol",
    "8-25": ["San Ginés de Arlés", "San José de Calasanz", "Santa Patricia"],
    "8-26": "Santa Teresa de Jesús Jornet",
    "8-27": "Santa Mónica",
    "8-28": "San Agustín de Hipona",
    "8-29": "San Juan Bautista (Martirio)",
    "8-30": "San Pamaquio de Roma",
    "8-31": "San Ramón Nonato",
    
    "9-1": "San Josué",
    "9-2": "Beato Bartolomé Gutiérrez",
    "9-3": "San Gregorio Magno",
    "9-4": "San Moisés",
    "9-5": "Beata Teresa de Calcuta",
    "9-7": "Santa Regina de Autun",
    "9-8": ["Virgen de Nuria", "Natividad de María"],
    "9-9": "San Pedro Claver",
    "9-10": "San Nicolás de Tolentino",
    "9-11": "San Pafnucio de Egipto",
    "9-12": "Dulce Nombre de María",
    "9-13": "San Juan Crisóstomo",
    "9-14": "Exaltación de la Santa Cruz",
    "9-15": "Virgen de los Dolores",
    "9-16": ["San Cipriano", "San Cornelio", "San Juan Macías"],
    "9-17": ["San Roberto Belarmino", "Santa Adriana", "Santa Hildegarda"],
    "9-18": "San José de Cupertino",
    "9-19": "San Jenaro de Nápoles",
    "9-20": "San Andrés Kim Taegön",
    "9-21": "San Mateo Evangelista",
    "9-22": "San Mauricio de Agauno",
    "9-23": ["San Pío de Pietrelcina", "Santa Tecla"],
    "9-24": "Virgen de la Merced",
    "9-25": "San Cleofás",
    "9-26": ["San Cosme", "San Damián"],
    "9-27": "San Vicente Paúl",
    "9-28": ["San Lorenzo Ruiz", "San Wenceslao"],
    "9-29": ["San Gabriel", "San Miguel", "San Rafael"],
    "9-30": "San Jerónimo",
    
    "10-1": "Santa Teresita del Niño Jesús",
    "10-2": "Santos Ángeles Custodios",
    "10-3": "San Francisco de Borja",
    "10-4": "San Francisco de Asís",
    "10-5": ["San Froilán", "Santa Faustina Kowalska"],
    "10-6": "San Bruno de Colonia",
    "10-7": "Virgen del Rosario",
    "10-9": ["San Abrahán", "San Dionisio de París", "San Juan Leonardi"],
    "10-10": "Santo Tomás de Villanueva",
    "10-12": "Virgen del Pilar",
    "10-13": "San Eduardo III",
    "10-14": "San Calixto I",
    "10-15": "Santa Teresa de Ávila",
    "10-16": ["San Gerardo Mayela", "Santa Eduvigis", "Santa Margarita María"],
    "10-17": "San Ignacio de Antioquía",
    "10-18": "San Lucas Evangelista",
    "10-19": ["San Pablo de la Cruz", "San Pedro de Alcántara"],
    "10-20": ["San Honorio", "Santa Irene"],
    "10-21": ["Madre Laura", "Santa Úrsula"],
    "10-22": ["San Abercio", "San Juan Pablo II"],
    "10-23": "San Juan de Capistrano",
    "10-24": "San Antonio María Claret",
    "10-25": "San Frutos de Segovia",
    "10-26": "San Evaristo",
    "10-28": ["San Judas Tadeo", "San Simón"],
    "10-29": "San Narciso de Jerusalén",
    "10-30": "San Marcelo de León",
    "10-31": "San Alonso Rodríguez",
    
    "11-1": "Todos los Santos",
    "11-2": "Todos los Fieles Difuntos",
    "11-3": "San Martín de Porres",
    "11-4": "San Carlos Borromeo",
    "11-5": ["San Zacarías", "Santa Ángela de la Cruz", "Santa Isabel"],
    "11-6": "San Severo de Barcelona",
    "11-7": "San Ernesto",
    "11-8": "Beato Juan Duns Escoto",
    "11-9": ["Virgen de la Almudena", "Dedicación de Letrán"],
    "11-10": ["San Andrés Avelino", "San León Magno"],
    "11-11": "San Martín de Tours",
    "11-13": "San Diego de Alcalá",
    "11-14": "San José Pignatelli",
    "11-15": ["San Alberto Magno", "San Eugenio de Toledo"],
    "11-16": "Santa Margarita de Escocia",
    "11-17": ["San Gregorio Taumaturgo", "Santa Isabel de Hungría", "Santa Victoria"],
    "11-18": ["San Odón de Cluny", "Dedicación de San Pedro y San Pablo"],
    "11-19": "Profeta Abdías",
    "11-20": "San Edmundo",
    "11-21": "Presentación de María",
    "11-22": "Santa Cecilia de Roma",
    "11-23": "Beato Miguel Agustín Pro",
    "11-24": ["Santa Flora", "Santa María de Córdoba"],
    "11-25": "Santa Catalina de Alejandría",
    "11-26": "San Silvestre Gozzolini",
    "11-27": "La Medalla Milagrosa",
    "11-28": "Santa Catalina Labouré",
    "11-29": "San Saturnino de Tolosa",
    "11-30": "San Andrés Apóstol",
    
    "12-1": "San Eloy",
    "12-2": "Santa Bibiana",
    "12-3": "San Francisco Javier",
    "12-4": ["San Juan Damasceno", "Santa Bárbara"],
    "12-5": "San Sabas",
    "12-6": "San Nicolás de Bari",
    "12-7": "San Ambrosio de Milán",
    "12-8": "Inmaculada Concepción",
    "12-9": "San Juan Diego",
    "12-10": "Virgen de Loreto",
    "12-11": "San Dámaso I",
    "12-12": "Virgen de Guadalupe",
    "12-13": "Santa Lucía de Siracusa",
    "12-14": "San Juan de la Cruz",
    "12-15": "San Urbicio",
    "12-16": "Santa Adela",
    "12-17": "San Lázaro de Betania",
    "12-18": "Virgen de la Esperanza",
    "12-19": "Santa Eva",
    "12-20": "Santo Domingo de Silos",
    "12-21": "San Pedro Canisio",
    "12-23": ["San Antonio de Santa Ana Galvao", "San Juan de Kety"],
    "12-24": "San Gregorio de Spoleto",
    "12-25": ["Virgen del Belén", "Navidad de Jesucristo"],
    "12-26": "San Esteban",
    "12-27": "San Juan Evangelista",
    "12-28": "Santos Inocentes",
    "12-29": "Santo Tomas Becket",
    "12-30": ["Santa Judit", "Traslación de Santiago"],
    "12-31": ["San Silvestre I", "Santa Melania"]
};

// Función para obtener el santo del día
function getSantoDelDia() {
    const today = new Date();
    const month = today.getMonth() + 1;
    const day = today.getDate();
    const key = `${month}-${day}`;
    
    const santo = SANTOS_CALENDARIO[key];
    
    if (!santo) {
        return "Santo del día";
    }
    
    // Si es un array, devolver solo el primero (el más importante)
    if (Array.isArray(santo)) {
        return santo[0];
    }
    
    return santo;
}

// Función para obtener TODOS los santos del día
function getTodosLosSantos() {
    const today = new Date();
    const month = today.getMonth() + 1;
    const day = today.getDate();
    const key = `${month}-${day}`;
    
    const santo = SANTOS_CALENDARIO[key];
    
    if (!santo) {
        return [];
    }
    
    // Devolver array con todos los santos
    if (Array.isArray(santo)) {
        return santo;
    }
    
    return [santo];
}
